version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    command: bash -c "node build/server.js"
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - PORT=8000
      - PUBLIC_PATH=/
